server:
  port: 7002

eureka:
  instance:
    hostname: eureka2.com
  client:
    register-with-eureka: false   #不像eureka注册自己
    fetch-registry: false         #不去检索服务
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/