server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    #是否从 EurekaServer 抓取已有的注册信息，默认为 true。单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.wuhua.springcloud.service.PaymentService: debug